target_dir: data/segmentation
result_root_dir: result/segmentation
# train_dirs:
#     - train_1
#     - train_2
#     - validation

train_dirs:
  dataA:
    dirs:
      - train_1
    split: no
    total: 20
  dataB:
    dirs:
      - train_2
    split: yes
    total: all
nb_split: 5


test_dirs:
    - test
training: yes
task: segmentation # classification or segmentation is supported

train_params: 
    model_name: deeplab_v3
    backbone: mobilenetv2
    activation: softmax
    optimizer: adam
    loss:
      functions:
        CategoricalFocalLoss:
        DiceLoss:
    scheduler:
        functions:
            CosineDecay:
                lr_max: 0.001
                lr_min: 0.0001
    batch_size: 8 
    learning_rate: 0.001         
epochs: 2
segmentation_val_step: 2
n_trials: 3
width: 512
height: 256
input_dir: image
label_dir: label
trained_path:
result_dir: segmentation_result
class_names:
    - background
    - hoge
    - fuga
    - piyo
train_colors:
    - 0
    - 5
    - 10
    - 15
early_stopping: yes # yes if using early_stopping to interruption
patience: 5
monitor: val_loss
mlflow: True
experiment_name: test_experiment
run_name: segmentation_test
user_name: test_user
tracking_uri: './mlruns' # path to mlruns
data_dvc_path:
    'data_name': './data.dvc' # path to dvc
description: test
version: 0.0.0